---
Lucas Caramês R notas: Limpeza e tratamento de dados
---

```{r}
# importa dados, string vazio como NA, string como fatores
setwd("C:\\Users\\Lucas\\Downloads\\FormaçãoCD2 (1)\\todos os arquivos\\9.Prática em R\\dados")
dados = read.csv("Churn.csv", sep = ";", na.strings="", stringsAsFactors = T)
head(dados)
summary(dados)
```

Colunas
```{r}
# Dar nomes às colunas 

colnames(dados) = c("Id", "Score", "Estado", "Genero", "Idade", "Patrimonio", "Saldo", "Produtos", "TemCartCredito", "Ativo", "Salario", "Saiu")

head(dados)
```
Explorar dados, colunas categóricas
```{r}
# Estados
counts = table(dados$Estado)
barplot(counts, main="Estados", xlab="Estados")

#Genero
counts = table(dados$Genero)
barplot(counts, main="Gêneros", xlab="Gêneros")
```
Explorar colunas numéricas

```{r}
# Idade
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```
Saldo
```{r}
# Saldo
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
``` 
Salário
```{r}
# Idade
summary(dados$Salario)
boxplot(dados$Salario)
boxplot(dados$Salario, outline=F)
``` 

Valores faltantes - NAs
```{r}

dados[!complete.cases(dados),] # ! -> not
``` 
Salários
```{r}
# Tratar salário

# ver mediana
median(dados$Salario, na.rm = T)

# atribuir mediana a NAs
dados[is.na(dados$Salario),]$Salario = median(dados$Salario, na.rm = T)

dados[!complete.cases(dados$Salario),]
``` 
Falta de padronização em Gênero
```{r}
# ver valores
unique(dados$Genero)
summary(dados$Genero)
# Transformar F e Fem em feminino

# Transformar "" e M em masculino (moda)
dados[is.na(dados$Genero) | dados$Genero == "M",]$Genero = "Masculino"
dados[dados$Genero == "F" | dados$Genero == "Fem",]$Genero = "Feminino"

# Ver resultado
summary(dados$Genero)
# remover levels não utilizados
dados$Genero = factor(dados$Genero)

#visualizar novamente 
summary(dados$Genero)
``` 

Idades fora do domínio
```{r}
summary(dados$Idade)
#fora do domínio numérico - ver idades anormais
dados[dados$Idade<0 | dados$Idade>110,]$Idade

#verificar se há idade NAs
dados[is.na(dados$Idade),]

#opcao, preencher com mediana
median(dados$Idade)

# substituição
dados[dados$Idade<0 | dados$Idade>110,]$Idade = median(dados$Idade)

# buscamos novamente idades anormais
dados[dados$Idade<0 | dados$Idade>110,]
summary(dados$Idade)
``` 

Dados duplicados
```{r}
# buscar duplicados pelo ID
x = dados[duplicated(dados$Id),]
x

#verificamos que o ID 81 está dupllicado
#vamos excluir pelo ID, não pelo índice
dados = dados[ !dados$Id %in% c(x$Id),]
dados[dados$Id == x$Id,]
```
Estados fora do domínio
```{r}
# fora do domínio - categórico
unique(dados$Estado)
summary(dados$Estado)

# preencher com a moda, RS
dados[!dados$Estado %in% c("RS", "SC", "PR"),]$Estado = "RS"
summary(dados$Estado)
# removemos fatores não usados
dados$Estado = factor(dados$Estado)

#visualizar novamente
summary(dados$Estado)
``` 
Outliers
```{r}
# outlier, criando um parâmetro com desvio padrão
desv = sd(dados$Salario, na.rm = T)
dados[dados$Salario >= 2*desv,]$Salario

# outra forma, resultado semmelhante, mas em os NAs
boxplot(dados$Salario)
x = boxplot(dados$Salario)$out
x

#atualizamos todos para mediana
median(dados$Salario)
dados[dados$Salario >= 2*desv,]$Salario = median(dados$Salario)

#checamos se saíram os outliers
dados[dados$salario >= 2*desv,]$Salario
``` 